"""add reservation table and delete column status to rooms table

Revision ID: 68e22d11d04a
Revises: e54f0334d14a
Create Date: 2026-02-28 16:36:56.142211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68e22d11d04a"
down_revision: Union[str, Sequence[str], None] = "e54f0334d14a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("check_in_date", sa.DateTime(), nullable=False),
        sa.Column("check_out_date", sa.DateTime(), nullable=False),
        sa.Column("total_price", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "CANCELED",
                "COMPLETED",
                name="reservation_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("rooms", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "status",
            postgresql.ENUM("AVAILABLE", "OCCUPIED", "MAINTENANCE", name="status_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("reservation")
    # ### end Alembic commands ###
