"""column slug is required

Revision ID: 4d4989361879
Revises: 9adbab3e44f8
Create Date: 2026-02-10 17:40:38.023326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d4989361879"
down_revision: Union[str, Sequence[str], None] = "9adbab3e44f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("room_types", "slug", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("room_types", "slug", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
