"""initialization database

Revision ID: e54f0334d14a
Revises:
Create Date: 2026-02-26 23:38:21.713253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e54f0334d14a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "room_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("price_per_day", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("patronymic", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("passport_series", sa.String(length=4), nullable=False),
        sa.Column("passport_number", sa.String(length=6), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "EMPLOYEE", "GUEST", name="user_role_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint(
            "passport_series", "passport_number", name="unique_passport"
        ),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("advance", sa.Integer(), nullable=False),
        sa.Column("hire_date", sa.DateTime(), nullable=False),
        sa.Column("bank_account", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "FIRED", "ON_LEAVE", "PROBATION", name="employee_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("fired_date", sa.DateTime(), nullable=True),
        sa.Column("weekends", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "room_type_amenities",
        sa.Column("room_type_id", sa.Integer(), nullable=False),
        sa.Column("amenity_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_main", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
        ),
        sa.PrimaryKeyConstraint("room_type_id", "amenity_id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("quantity_places", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "OCCUPIED", "MAINTENANCE", name="status_enum"),
            nullable=False,
        ),
        sa.Column("room_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    op.drop_table("room_type_amenities")
    op.drop_table("employee")
    op.drop_table("user")
    op.drop_table("room_types")
    op.drop_table("position")
    op.drop_table("amenities")
    # ### end Alembic commands ###
