"""create rooms table

Revision ID: 4011e02336bb
Revises: 146f92518057
Create Date: 2026-02-09 22:35:39.829483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4011e02336bb"
down_revision: Union[str, Sequence[str], None] = "146f92518057"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("quantity_places", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "OCCUPIED", "MAINTENANCE", name="status_enum"),
            nullable=False,
        ),
        sa.Column("room_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
