"""add columns image and flag is_main to Amenities

Revision ID: 091ce5543649
Revises: c70ac777b310
Create Date: 2026-02-09 23:50:54.753393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "091ce5543649"
down_revision: Union[str, Sequence[str], None] = "c70ac777b310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("amenities", sa.Column("image", sa.String(), nullable=True))
    op.add_column(
        "amenities",
        sa.Column(
            "is_main", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("amenities", "is_main")
    op.drop_column("amenities", "image")
    # ### end Alembic commands ###
