"""delete column image to amenities

Revision ID: caee9614425c
Revises: 4d4989361879
Create Date: 2026-02-15 14:59:59.397816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "caee9614425c"
down_revision: Union[str, Sequence[str], None] = "4d4989361879"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("amenities", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "amenities", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
