"""create employee and position tables

Revision ID: 1ff922362d33
Revises: bd4921fa249d
Create Date: 2026-02-17 23:57:50.814237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1ff922362d33"
down_revision: Union[str, Sequence[str], None] = "bd4921fa249d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("advance", sa.Integer(), nullable=False),
        sa.Column("hire_date", sa.DateTime(), nullable=False),
        sa.Column("bank_account", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "FIRED", "ON_LEAVE", "PROBATION", name="employee_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("fired_date", sa.DateTime(), nullable=True),
        sa.Column("weekends", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee")
    op.drop_table("position")
    # ### end Alembic commands ###
