"""add column slug to room-types table

Revision ID: 9adbab3e44f8
Revises: e2d26edba477
Create Date: 2026-02-10 17:31:57.504824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9adbab3e44f8"
down_revision: Union[str, Sequence[str], None] = "e2d26edba477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("room_types", sa.Column("slug", sa.String(), nullable=True))
    op.create_unique_constraint(None, "room_types", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room_types", type_="unique")
    op.drop_column("room_types", "slug")
    # ### end Alembic commands ###
